name: Build

on:
  push:
    branches: [ "master" ]
    tags: [ "v*" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check-and-test:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
    - uses: actions/checkout@v3
    
    - name: Install clippy
      run: rustup component add clippy
    
    - name: Run clippy
      run: cargo clippy -- -D warnings
      
    - name: Run tests
      run: cargo test --verbose

  build-mac-intel:
    runs-on: macos-11  # Big Sur
    if: github.event_name == 'push' && (github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/'))
    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependencies
      run: |
        brew install create-dmg
        cargo install cargo-bundle
    
    - name: Build
      run: cargo build --verbose
      
    - name: Run tests
      run: cargo test --verbose
      
    - name: Create App Bundle and DMG
      run: |
        chmod +x build.sh
        ./build.sh
        
    - name: Upload DMG as artifact
      uses: actions/upload-artifact@v4
      with:
        name: Pinger-Mac-Intel
        path: Pinger.dmg

    - name: Create Release (Intel)
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: Pinger.dmg
        draft: false
        prerelease: false
        name: Pinger-Intel.dmg
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-mac-silicon:
    runs-on: macos-14  # Latest macOS for M1/M2
    if: github.event_name == 'push' && (github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/'))
    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependencies
      run: |
        brew install create-dmg
        cargo install cargo-bundle
    
    - name: Build
      run: cargo build --verbose
      
    - name: Run tests
      run: cargo test --verbose
      
    - name: Create App Bundle and DMG
      run: |
        chmod +x build.sh
        ./build.sh
        
    - name: Upload DMG as artifact
      uses: actions/upload-artifact@v4
      with:
        name: Pinger-Mac-Silicon
        path: Pinger.dmg

    - name: Create Release (Silicon)
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: Pinger.dmg
        draft: false
        prerelease: false
        name: Pinger-Silicon.dmg
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-other:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install Linux dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtk-3-dev libglib2.0-dev libxdo-dev

    - name: Build
      run: cargo build --verbose
      
    - name: Run tests
      run: cargo test --verbose 