name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        
      - name: Install cargo-bundle
        run: cargo install cargo-bundle
        
      - name: Install create-dmg
        run: brew install create-dmg
        
      - name: Build Release
        run: |
          cargo bundle --release
          create-dmg \
            --volname "Pinger" \
            --window-pos 200 120 \
            --window-size 800 400 \
            --icon-size 100 \
            --icon "Pinger.app" 200 190 \
            --hide-extension "Pinger.app" \
            --app-drop-link 600 185 \
            "Pinger.dmg" \
            "target/release/bundle/osx/Pinger.app"

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: Pinger.dmg
          body_path: CHANGELOG.md
          draft: false
          prerelease: false 